# Generated by Django 4.1 on 2022-08-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
